### ISSUE TITLE
Volume below MinBuyVolume setting disables DCA buying

### ISSUE THREAD

**Issue by Brillynt** [mehtadone/PTFeeder#174]
Currently when the MinBuyVolume is higher than the volume for a pair, it is put in SOM.  This disables being able to buy for DCA if needed.  Could this be changed so that the pair is not in SOM and instead the volume is set for the pair and then it would still be able to use the PT DCA volume setting.  I would also  suggest adding the PT DCA min_buy_volume setting to the PTF DCA settings.  This issue happens when the volume for a pair drops below the MinBuyVolume after it has been purchased.

**Comment by mehtadone** [comment]
Wouldnt adding/changing this property in your dca.txt do the trick?

ignore_sell_only_mode = true

Set this value to true to allow DCA to continue buying even if no new buys are allowed. This is often used when you want the bot to stop buying new coins, but get rid of existing coins.

https://wiki.profittrailer.io/doku.php/dca.properties

**Comment by smoochy** [comment]
I am supporting the idea, Brillynt has and want to add another thought to why it is helpful:

I am working with `All_btc_price_drop_trigger` and an `ALL_btc_price_rise_trigger` to protect me from huge market swings.
I also like to set `ignore_sell_only_mode = false` in my `dca.properties`. Because of the huge swings we had. I don't want to DCA when the market is going down and down.

Situation is like the last days. In the past 3 days the coins went down a lot, hence small gaps and low buy triggers would not really help for DCA. Buy triggers like -5, -10, -15 would have been ok for the past days. Even though it was a boring / bearish market according to `MaxTopCoinAverageChange`. `ignore_sell_only_mode = false` would have been advised.

Today, it was again a boring / bearish market. But the coins did not drop so much. Hence buy triggers like -5, -10 etc would not be beneficial. Buy triggers like -1.5, -3,5, -6 or so would be ok. And `ignore_sell_only_mode = true` would have been ok.

So I would need to adjust my settings everydays. Which kind of forfeits the advantages of a bot.

Hence I would rather like to have small buy triggers in my DCA file all the time, as they are only executed, when SOM is not active. But this is not happening right now, as the coin in DCA can not be bought, as volume of this coin dropped below my `MinBuyVolume`.

Just to give you an example: 

![som](https://user-images.githubusercontent.com/34371932/36398254-7901e3ae-15c6-11e8-8fff-114bdd8e468f.jpg)

I am currently not allowed to DCA WTCBTC further, though I would have the balance for it and PT is not in SOM mode, because the volume is below my `MinBuyVolume`.

There is a `min_buy_volume` setting in `dca.properties` (and I set it to 50), but it is ignored by PTF:

> #------------------BTC/WTC------------------
> # WTCBTC has been set to SELL ONLY mode
> # Price change (60): -1.29%
> # Price change (1440): -2.15%
> # Upside volatility: 0.25%
> # Downside volatility: 0.1%
> # Sell Only Mode Reasons:
>  # Pair volume 426.5716712222 is less than the min buy volume of 700
> 
> 
> WTCBTC_trading_enabled = true
> WTCBTC_trailing_profit = 0.125
> WTCBTC_DCA_enabled = -1.5
> WTCBTC_sell_value = 0.5
> WTCBTC_sell_only_mode = true
> #------------------------------------


I would like to suggest a new value like `DcaMinBuyVolume`. 
As long as the coin is in DCA (not in normal pairs log), and global SOM is not active, and the volume of this coin is above `DcaMinBuyVolume`, it is DCAing it.


I hope I expressed myself somewhat clear. If you have further questions, please let me know. If you want to, we can also continue the talk on discord again. 

Thanks for reading and maybe considering it. PTF is a wonderful tool.

**Comment by mehtadone** [comment]
@smoochy can you not add min_buy_volum in your dca.txt file for the time being? I'll look to generate it in the PTF soon but for the interim would that not work?

**Comment by smoochy** [comment]
I have that added. I have set it to 50, like written above (just above the big quote).
But it is ignored, as PTF sets the whole coin into SOM in pairs.properties. So the MinBuyVolume from DCA.txt (and DCA.properties in PT/trading is never executed.
