### ISSUE TITLE
Please Add pt-feeder Windows Batch File

### ISSUE THREAD

**Issue by TheCryptoClown** [mehtadone/PTFeeder#221]
Hi. Your newest version of PT-Feeder did not contain a BAT file in order to open up Feeder. Instead, it seems I had to manually open it using the Command Prompt Window. I know you can create a BAT file, but it would be easier if you simply had one in the downloads as with previous versions just to save a step.

I am requesting for your next update release of Feeder, a Windows Batch File be included.

Thank you.

-Jonathan

**Comment by mehtadone** [comment]
The reason why it was excluded is that new users of PT Feeder were using the bat file start the application, which hid any error messages in setup. It was removed so that users know how to start itup manually and thus can see any setup errors. 

I understand that it is one extra step once you get it running, but unfrotunately this was the only way we could help educate users on how to run it manually.

**Comment by TheCryptoClown** [comment]
Oh, I understand. Thank you for letting me know.


Have a wonderful weekend!

On Thu, Mar 01, 2018 at 04:49 AM, mehtadone wrote:

The reason why it was excluded is that new users of PT Feeder were using 
the bat file start the application, which hid any error messages in 
setup. It was removed so that users know how to start itup manually and 
thus can see any setup errors.

I understand that it is one extra step once you get it running, but 
unfrotunately this was the only way we could help educate users on how 
to run it manually.


—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub 
<https://github.com/mehtadone/PTFeeder/issues/221#issuecomment-369537494> 
, or mute the thread
