### ISSUE TITLE
Can't find prices on Binance with incorrect symbols

### ISSUE THREAD

**Issue by vincev1975** [mehtadone/PTFeeder#245]
I am running PTF on Binance and I get the following errors that the bot can't find prices on coins that are not in Binance format ex xxxBTC.  This log is being displayed on every run and it clogs up the logfile.  Could you fix this query please?:  If one is trading on Binance please use only analysis on Binance coins with Binance symbols used in the query.. of course other coins on other exchanges will have zero price!

https://www.screencast.com/t/feIpCjP6cJj

**Comment by mehtadone** [comment]
These are coins that have been returned by the binance api.

If the api reports them as valid coins, then PTF has to show them, there is no way to know that they are not traded from the api

**Comment by vincev1975** [comment]
BTC/ELC, BTC/HCC are valid coins on the Binance exchange you think with this symbol? 
____________________________________________________________
Unbelievable German World War 2 Photo Stuns Americans
pro.naturalhealthresponse.com
http://thirdpartyoffers.juno.com/TGL3131/5aa0101e24735101d1382st03vuc

**Comment by mehtadone** [comment]
They might not be valid coins on exchange but they have been returned to PTF via the api otherwise how would it know about them?

Binance might have sent them by mistake, and if this is the case, then PTF will remove them on next restart or when it checks for supported symbols again, which is every hour
