### ISSUE TITLE
Suggestion: Volume Change Grouping

### ISSUE THREAD

**Issue by robotlovefarm** [mehtadone/PTFeeder#329]
Can we have Volume Change grouping?
For example, SOM to coins with very high growth in volume, example:
# Volume change (60): -55.08%
# Volume change (1440): 6030.28%

Thanks

**Comment by mehtadone** [comment]
It is possible at the moment but the issue is that the current candle volume is compared with the volume of the candle, 60 or 1440 mins ago. The volume varies a lot candle to candle so this isn't a good indicator of volume increase. There will be something more stable coming soon. If you would like to use this, the grouping names are: 

```
VolumeTrendChange
LongerTermVolumeChange
```

and the trigger name is `MaxVolumeTrendPercentageChange` for both.
